describe('Dzemat management app', () => {
  beforeEach(() => {
    cy.visit('https://dzematmgmt-dev.uradinesto.ba/login')
    cy.get('h1').should("be.visible")
    cy.get('#usernameOrEmail').should("be.visible")
    cy.get('#password').should("be.visible")
    cy.get(':nth-child(3) > .MuiButtonBase-root').should("be.visible")
    cy.get('a').should("be.visible")
    cy.get('#usernameOrEmail').type("admin")
    cy.get('#password').type("admin")
    cy.get(':nth-child(3) > .MuiButtonBase-root').click()
  })
  it('DP-1 Verify that admin user can login to Dzemat MGMT webpage', () => {
    cy.get('.logo-img').should("be.visible")
    cy.url().should('eq', 'https://dzematmgmt-dev.uradinesto.ba/admin/home')
  })

  it('DP-2 Verify the content of the Dzemat MGMT homepage', () => {
    cy.get('.logo-img').should("be.visible")
    cy.get('.navbar-list > :nth-child(1)').should("be.visible")
    cy.get('.navbar-list > :nth-child(2)').should("be.visible")
    cy.get('.navbar-list > :nth-child(3)').should("be.visible")
    cy.get('.navbar-list > :nth-child(4)').should("be.visible")
    cy.get('.navbar-list > :nth-child(5)').should("be.visible")
    cy.get('.navbar-list > :nth-child(6)').should("be.visible")
    cy.get('.navbar-list > :nth-child(7)').should("be.visible")
    cy.get('.navbar-list > :nth-child(8)').should("be.visible")
    cy.get('.navbar-list > :nth-child(9)').should("be.visible")
    cy.get('.navbar-list > :nth-child(10)').should("be.visible")
    cy.get('.navbar-list > :nth-child(11)').should("be.visible")
    cy.get(':nth-child(12)').should("be.visible")
    cy.get(':nth-child(1) > .cta-content').should("be.visible")
    cy.get(':nth-child(2) > .cta-content').should("be.visible")
    cy.get(':nth-child(3) > .cta-content').should("be.visible")
    cy.get(':nth-child(4) > .cta-content').should("be.visible")
    cy.get(':nth-child(5) > .cta-content').should("be.visible")
    cy.get(':nth-child(6) > .cta-content').should("be.visible")
    cy.get(':nth-child(7) > .cta-content').should("be.visible")
    cy.get(':nth-child(8) > .cta-content').should("be.visible")
    cy.get(':nth-child(9) > .cta-content').should("be.visible")
    cy.get('.collapse-wrapper').should("be.visible")
    cy.get('.copyright').should("be.visible")
  })
  it('DP-3 Add "džemat" in module "Početna" on Džemat MGMT dev env', () => {
    cy.get(':nth-child(1) > .cta-content > .cta-title').should("be.visible")
    cy.get(':nth-child(1) > .cta-content > .cta-description').should("be.visible")
    cy.get(':nth-child(1) > .cta-content > .mdc-button > .mdc-button__ripple').should("be.visible")
    cy.get(':nth-child(1) > .cta-content > .mdc-button > .mdc-button__label').click()
    cy.url().should('eq', 'https://dzematmgmt-dev.uradinesto.ba/admin/jamaats/add')
    cy.get('h1').should("be.visible")
    cy.get('#name').should("be.visible")
    cy.get('.MuiButtonBase-root').should("be.visible")
    cy.get('#name').type("Test title")
    cy.get('.MuiButtonBase-root').click()
    cy.get('.navbar-list > :nth-child(4)').click()
    cy.url().should('eq', 'https://dzematmgmt-dev.uradinesto.ba/admin/jamaats')
    cy.get('.cta-content').should("be.visible")
    cy.get('.cta-title').should("be.visible")
    cy.get('.cta-description').should("be.visible")
    cy.get('.mdc-button__ripple').should("be.visible")
    cy.get('.page-section-main-content > :nth-child(2)').should("be.visible")
    cy.get('#searchField').should("be.visible")
    cy.get('.MuiInputAdornment-root > .MuiButtonBase-root').should("be.visible")
    cy.get('[tabindex="0"] > .MuiDataGrid-columnHeaderDraggableContainer > .MuiDataGrid-columnHeaderTitleContainer').should("be.visible")
    cy.get('[aria-colindex="2"] > .MuiDataGrid-columnHeaderDraggableContainer > .MuiDataGrid-columnHeaderTitleContainer > .MuiDataGrid-columnHeaderTitleContainerContent > .MuiDataGrid-columnHeaderTitle').should("be.visible")
    cy.get('[aria-colindex="3"] > .MuiDataGrid-columnHeaderDraggableContainer > .MuiDataGrid-columnHeaderTitleContainer > .MuiDataGrid-columnHeaderTitleContainerContent > .MuiDataGrid-columnHeaderTitle').should("be.visible")
    cy.get('[data-id="89"] > [data-field="name"] > .MuiDataGrid-cellContent').should('contain' ,'Test')
  })
  it('DP-4 Add "imam" in module "Početna" on Džemat MGMT dev env', () => {
    cy.get(':nth-child(2) > .cta-content > .cta-title').should("be.visible")
    cy.get(':nth-child(2) > .cta-content > .cta-description').should("be.visible")
    cy.get(':nth-child(2) > .cta-content > .mdc-button > .mdc-button__ripple').should("be.visible")
    cy.get(':nth-child(2) > .cta-content > .mdc-button > .mdc-button__label').click()
    cy.url().should('eq', 'https://dzematmgmt-dev.uradinesto.ba/admin/imams/add')
    cy.get('h1').should("be.visible")
    cy.get('#fname').should("be.visible")
    cy.get('#lname').should("be.visible")
    cy.get('#fatherName').should("be.visible")
    cy.get('#jmbg').should("be.visible")
    cy.get('#birthPlace').should("be.visible")
    cy.get('#jamaat').should("be.visible")
    cy.get('#education').should("be.visible")
    cy.get('.MuiFormControlLabel-root').should("be.visible")
    cy.get('.MuiFormControl-root > .MuiButtonBase-root').should("be.visible")
    cy.get('#fname').type("Merima")
    cy.get('#lname').type("Test")
    cy.get('#fatherName').type("Samir")
    cy.get('#jmbg').type("6666666666666666")
    cy.get('.MuiStack-root > .MuiFormControl-root > .MuiInputBase-root').type('20021988')
    cy.get('#birthPlace').type("Sanski Most")
    cy.get('#education').click()
    cy.get('[data-value="2"]').click()
    cy.get('.MuiFormControl-root > .MuiButtonBase-root').click()
    cy.get('.navbar-list > :nth-child(2)').click()
    cy.url().should('eq', 'https://dzematmgmt-dev.uradinesto.ba/admin/imams')
    cy.get('.cta-content').should("be.visible")
    cy.get('.cta-title').should("be.visible")
    cy.get('.cta-description').should("be.visible")
    cy.get('.mdc-button__ripple').should("be.visible")
    cy.get('.page-section-main-content > :nth-child(2)').should("be.visible")
    cy.get('#searchField').should("be.visible")
    cy.get('.MuiInputAdornment-root > .MuiButtonBase-root').should("be.visible")
    cy.get('[tabindex="0"] > .MuiDataGrid-columnHeaderDraggableContainer > .MuiDataGrid-columnHeaderTitleContainer').should("be.visible")
    cy.get('[aria-colindex="2"] > .MuiDataGrid-columnHeaderDraggableContainer > .MuiDataGrid-columnHeaderTitleContainer').should("be.visible")
    cy.get('[aria-colindex="3"] > .MuiDataGrid-columnHeaderDraggableContainer > .MuiDataGrid-columnHeaderTitleContainer').should("be.visible")
    cy.get('[aria-colindex="4"] > .MuiDataGrid-columnHeaderDraggableContainer > .MuiDataGrid-columnHeaderTitleContainer').should("be.visible")
    cy.get('[aria-colindex="5"] > .MuiDataGrid-columnHeaderDraggableContainer > .MuiDataGrid-columnHeaderTitleContainer').should("be.visible")
    cy.get('[aria-colindex="6"] > .MuiDataGrid-columnHeaderDraggableContainer > .MuiDataGrid-columnHeaderTitleContainer').should("be.visible")
    cy.get('[aria-colindex="7"] > .MuiDataGrid-columnHeaderDraggableContainer > .MuiDataGrid-columnHeaderTitleContainer > .MuiDataGrid-columnHeaderTitleContainerContent > .MuiDataGrid-columnHeaderTitle').should("be.visible")
    cy.get('[aria-colindex="8"] > .MuiDataGrid-columnHeaderDraggableContainer > .MuiDataGrid-columnHeaderTitleContainer').should("be.visible")
    cy.get('[data-id="22"] > [data-field="fname"] > .MuiDataGrid-cellContent').should('contain' ,'Merima')
  })
  it('DP-5 Add "blagajnik" in module "Početna" on Džemat MGMT dev env', () => {
    cy.get(':nth-child(3) > .cta-content > .cta-title').should("be.visible")
    cy.get(':nth-child(3) > .cta-content > .cta-description').should("be.visible")
    cy.get(':nth-child(3) > .cta-content > .mdc-button > .mdc-button__ripple').should("be.visible")
    cy.get(':nth-child(3) > .cta-content > .mdc-button > .mdc-button__label').click()
    cy.url().should('eq', 'https://dzematmgmt-dev.uradinesto.ba/admin/treasurer/add')
    cy.get('h1').should("be.visible")
    cy.get('#fname').should("be.visible")
    cy.get('#lname').should("be.visible")
    cy.get('#fatherName').should("be.visible")
    cy.get('#jmbg').should("be.visible")
    cy.get('#birthPlace').should("be.visible")
    cy.get('.MuiInputAdornment-root > .MuiButtonBase-root').should("be.visible")
    cy.get(':nth-child(7) > .MuiButtonBase-root').should("be.visible")
    cy.get('#fname').type("Merima")
    cy.get('#lname').type("Test Dva")
    cy.get('#fatherName').type("Sanel")
    cy.get('#jmbg').type("9999999999999999")
    cy.get('#birthPlace').type("Peking")
    cy.get('.MuiStack-root > .MuiFormControl-root > .MuiInputBase-root').type('15021984')
    cy.get(':nth-child(7) > .MuiButtonBase-root').click()
    cy.get('.navbar-list > :nth-child(3)').click()
    cy.url().should('eq', 'https://dzematmgmt-dev.uradinesto.ba/admin/treasurers')
    cy.get('[data-id="9"] > [data-field="fname"] > .MuiDataGrid-cellContent').should('contain' ,'Merima')
  })
  it('DP-6 Add "domaćinstvo" in module "Početna" on Dzemat MGMT webpage', () => {
    cy.get(':nth-child(4) > .cta-content > .cta-title').should("be.visible")
    cy.get(':nth-child(4) > .cta-content > .cta-description').should("be.visible")
    cy.get(':nth-child(4) > .cta-content > .mdc-button > .mdc-button__ripple').should("be.visible")
    cy.get(':nth-child(4) > .cta-content > .mdc-button > .mdc-button__label').click()
    cy.url().should('eq', 'https://dzematmgmt-dev.uradinesto.ba/admin/households/add')
    cy.get('h1').should("be.visible")
    cy.get('#address').should("be.visible")
    cy.get('#phoneHome').should("be.visible")
    cy.get('#phoneMobile').should("be.visible")
    cy.get('#jamaat').should("be.visible")
    cy.get('.MuiStack-root > .MuiFormControl-root > .MuiInputBase-root').should("be.visible")
    cy.get('#email').should("be.visible")
    cy.get(':nth-child(2) > .MuiFormControlLabel-root').should("be.visible")
    cy.get(':nth-child(3) > .MuiFormControlLabel-root').should("be.visible")
    cy.get(':nth-child(4) > .MuiFormControl-root > .MuiInputBase-root').should("be.visible")
    cy.get('.MuiFormControl-root > .MuiButtonBase-root').should("be.visible")
    cy.get('#address').should("be.visible")
    cy.get('#address').type("Terazije 11")
    cy.get('#phoneHome').type("033 333 333")
    cy.get('#phoneMobile').type("062 222 222")
    cy.get('#jamaat').click()
    cy.get('[data-value="6"]').click()
    cy.get('.MuiStack-root > .MuiFormControl-root > .MuiInputBase-root').type('01012025')
    cy.get('#email').type("merima_hrapovic@hotmail.com")
    cy.get(':nth-child(4) > .MuiFormControl-root > .MuiInputBase-root').type("Domaćinstvo broji tri člana.")
    cy.get('.MuiFormControl-root > .MuiButtonBase-root').click()
    cy.get('.navbar-list > :nth-child(5)').click()
    cy.url().should('eq', 'https://dzematmgmt-dev.uradinesto.ba/admin/households')
    cy.get('.page-section-main-content').should("be.visible")
  })
})